### PR TITLE
Add Inheritance Python

### LINKED ISSUE #291: [Entry Request] Python: Inheritance
## Description

Write an "Inheritance" entry in the Python topic.

General topic: https://www.codecademy.com/resources/docs/python

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [ ] Assignee is added

### PR DESCRIPTION
**Pull request by Tawishi**
### Description

Adds topic `Inheritance in Python` in the docs. Also added images in the *media* folder for insertion in the entry.
resolves #291

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by yangc95** [comment]
Hi @Tawishi ,

Thanks for doing a self-review.

Upon my review, I noted that the entry in this PR contains text from [OOP Python Tutorials](https://www.python-course.eu/python3_inheritance.php). Notably, the code snippets and introductory paragraph (below):
> Inheritance is an object-oriented programming concept where a class derives attributes and behaviors from another class, eliminating the need to implement them again.

As for this PR, we have two options. I may either suggest changes upon which you may make the corresponding corrections, or I may take over this entry and directly make changes. Please let me know what you feel comfortable with and we can continue on to the next step.

> We take plagiarism seriously for Codecademy Docs and for Codecademy content in general because a single case of plagiarism could jeopardize the credibility of all other 650+ entries as well as our greater catalog.
> Here's the [Codecademy Docs Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md) on GitHub. Since this is the first occurrence, I am issuing a warning.
>
> We truly appreciate your help with your contribution so far and we don't want to lose you temporarily or permanently. But as we attempt to build the best coding documentation on the web, it's a long-term game and we want to focus on quality, not quantity!
> 
> We hope you understand why we are taking this very seriously. Feel free to email our Senior Curriculum Manager, Sonny, at sonny@codecademy.com if you have any questions.

Warmly,
Christine

**Comment by yangc95** [comment]
@Tawishi Love the spirit!

I've made quite a number of comments/suggestions. Please look over those and make the necessary changes. Once you are complete, let me know!

**Comment by yangc95** [comment]
> @yangc95 I have made the requested changes. Please review and let me know if any more changes are needed.

Cool, I'm going to make some edits directly to the entry to help speed up the process. 

I'll definitely let you know if any more changes are needed. Nice work on getting a bit creative with these code examples~

**Comment by yangc95** [comment]
@Tawishi It's getting there! We'll get at least one more review before moving on to the next step.
Thanks for your perseverance and work~

**Comment by Tawishi** [comment]
Thank you @yangc95 @caupolicandiaz and all the other maintainers for your patience and help. Hope to contribute again!

**Comment by sonnynomnom** [comment]
Making some changes: https://github.com/Codecademy/docs/commit/75e55ab07c6d265393d7728b2bb0703e80b916a3

**Pull request merged**
