### PR TITLE
added What is Server-side Rendering

### PR DESCRIPTION
**Pull request by irffanasiff**
### Description

Wrote a "What is Server-side Rendering?" article in the General section which solves #279. I have done some research and completed the server-side rendering article. Here i have explained about server-side rendering, whiy is it important and where is it useful. I have also pointed out where server side rendering cannot be used. 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by sonnynomnom** [comment]
Hi @demonicirfan, please sign the CLA and a maintainer will start reviewing it!

**Comment by demonicirfan** [comment]
> Hi @demonicirfan, please sign the CLA and a maintainer will start reviewing it!

Done what about these tests that are failing can you guide me in this please

**Comment by sonnynomnom** [comment]
Yep, don't worry about that for now! We are going to have people review your entry first!

**Comment by yangc95** [comment]
> > Hi demonicirfan, please sign the CLA and a maintainer will start reviewing it!
> 
> Done what about these tests that are failing can you guide me in this please

Hi @demonicirfan! You can refer to the [PR template](https://raw.githubusercontent.com/Codecademy/docs/main/.github/PULL_REQUEST_TEMPLATE.md) for failing tests! I can also go into your branch and run these scripts if you are having any difficulty.

**Comment by demonicirfan** [comment]
Do I have to change all this what @yangc95 and @EugeneGohh has suggested or changed.

**Comment by Dusch4593** [comment]
> I have one doubt the changes that @yangc95 and @EugeneGohh made are comitted or should i commit them @Dusch4593

It looks like the changes @yangc95 and @EugeneGohh recommended are outdated, so you'll have to make the changes locally and push up to this branch. Let me know once you've done that.

**Comment by yangc95** [comment]
@Dusch4593 Looks like a start to server-side rendering!

**Comment by yangc95** [comment]
> LGTM!

What do you think @sonnynomnom! Is this ready to be merged?

**Comment by sonnynomnom** [comment]
Yep, merged!

Congrats @demonicirfan! Just saw your LinkedIn post :)

I made some tiny changes here: https://github.com/Codecademy/docs/commit/813bc4d508063d8b5233925d3f17a94f3b3d5ece

Take a look when you get the chance @demonicirfan @yangc95 @Dusch4593 @EugeneGohh.

**Pull request merged**
