### PR TITLE
Add Python String Method `index()`

### PR DESCRIPTION
**Pull request by balapriyac**
### Description

Hi, I've added the `index()` method for Python strings. I had earlier created an entry for the `find()` method. The `index()` method works a lot like the `find()` method except that it raises a `ValueError` when the substring is not found. I've created the entry to be consistent with other string methods and similar to the `find()` method entry that I've created earlier.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Dusch4593** [comment]
Hi, @balapriyac! Thank you for these entries. I'd be happy to do the first review, which should be finished in the next 24 hours.

**Comment by balapriyac** [comment]
Thanks a bunch @Dusch4593, I'll start working on the suggestions in a bit.

**Comment by yangc95** [comment]
Nice one @balapriyac, this LGTM! @sonnynomnom

**Comment by sonnynomnom** [comment]
Hi @balapriyac, congrats on your merge! The entry is live here: https://www.codecademy.com/resources/docs/python/strings/index

I also went in and made some more changes: https://github.com/Codecademy/docs/commit/1e2a91f9e546cfd65c8449da7ce7253352fc1013

Take a look when you get a chance @balapriyac @Dusch4593 @yangc95 

Notably:
- The description metadata should start with a verb and no single ticks. Or else it will look like:

Screen Shot 2021-10-30 at 1 42 20 PM

- Only 2 items in the CatalogContent, not 3.
- Edited the parameters bullet points a little bit.
- Added the triple tick error code block.
- Missed one `index()` -> `.index()`.

**Pull request merged**
