### PR TITLE
Subroutines

### PR DESCRIPTION
**Pull request by ramanic**
### Description
Added a new entry ' What is subroutine ?'

### Type of Change

- Adding a new entry

### Checklist
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by yangc95** [comment]
Hi @ramanic, I'm going to be one of your reviewers for this entry.

I'll make sure to tag you once I finish with my suggestions/comments. Afterward, you may make any changes to the file, and then I may approve of the PR. 

Thanks for your contribution!

**Comment by sonnynomnom** [comment]
Yep, this already got two reviews, so we should be good!

**Comment by Dusch4593** [comment]
Hi @ramanic! Brandon from the Free Team 👋 

I was wondering about something regarding the files you made changes to in this PR compared to the contributors credited on the live entries. 😄 

You seem to be credited on the ones for [.isFinite()](https://www.codecademy.com/resources/docs/javascript/number-methods/isFinite) and [.isInteger()](https://www.codecademy.com/resources/docs/javascript/number-methods/isInteger). 👍 

Screen Shot 2022-03-10 at 9 53 39 AM

However, only "Anonymous" is listed among credited contributors on the entry for [General: Subroutines](https://www.codecademy.com/resources/docs/general/subroutine):

Screen Shot 2022-03-10 at 9 53 23 AM

Any thoughts as to why this might be? I'd love for you to receive credit for all of these entries but especially for "Subroutines" because you wrote the entirety of it, pretty much. Happy to help in any way that i can. 😄

**Comment by ramanic** [comment]
@Dusch4593  Yeah looks like there has been some mixup. I did contributed to Subroutines but I don't remember changing anything in  [.isFinite()](https://www.codecademy.com/resources/docs/javascript/number-methods/isFinite) and [.isInteger()](https://www.codecademy.com/resources/docs/javascript/number-methods/isInteger).

**Comment by Dusch4593** [comment]
@ramanic Sorry about this! I had a feeling 😭 Somehow, `isFinite.md` and `isInteger.md` were included in [the PR](https://github.com/Codecademy/docs/pull/331/files) you wrote for Subroutines.

But I'm still wondering how your profile is displayed for those entries but not for Subroutines? I wonder if logging out and re-logging into your Codecademy profile (through GitHub) would fix this?

**Pull request merged**
