### PR TITLE
Java/JavaScript: Add `ArrayList`/`toLocaleDateString()` entries

### PR DESCRIPTION
**Pull request by Vivek-Prajapatii**
### Description

Fixes issues #187 and #366.

### Type of Change

- Adding two new entries

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Dusch4593** [comment]
Hi @Vivek-Prajapatii! I'm so glad that you've gotten a chance to help us out with these two entries! I'm going to conduct the first review of your changes but I wanted to mention a couple of things regarding future PRs:

- If you're submitting more than one entry at a time, that's awesome! But if they span different languages, I highly recommend creating two separate PRs. 
- Make sure to name your branches and PRs after the changes you are making. This was one of the list items you checked at the beginning of this thread.
- If you can, mention in the "Description" which Issue(s) a given PR is intended to fix. But it's not important if you don't do this, I can always add them later as I did with this one.

I'll go ahead and proceed with the review and tag you when I'm finished. Thanks again for these entries, my friend! 😄

**Comment by Dusch4593** [comment]
@Vivek-Prajapatii Were you still working on the changes? We would still like to work with you and your entries. Otherwise, we can close this PR effective Monday at noon (UTC+05:30).

**Comment by Dusch4593** [comment]
> again lint and format failed Im new to it so help me in that

@Vivek-Prajapatii Hey! Thanks for pushing through with us. We're super excited to continue working with you on these entries! You don't actually gotta worry about those particular checks, the `lint` and `format` ones. One of us, either me or one of the other reviewers, will take care of that. We just like to give you the chance to push your changes first before we push ours. 😄

**Comment by Dusch4593** [comment]
Hey @Vivek-Prajapatii I just reviewed your recent changes and it looks _much much_ better. Thank you so much for all your work thus far. I left some more comments/suggestions for you to resolve before we move on to the next review. 

Great work! 😃 👏

**Comment by sonnynomnom** [comment]
Congrats @Vivek-Prajapatii 🚀

The entry is live: https://www.codecademy.com/resources/docs/java/array-list

I also made some more small changes: https://github.com/Codecademy/docs/commit/8b5272039230e8fd2821e16ce99d9b741f2fc9f6

Please take a look @Dusch4593 @yangc95.

And one more thing @Vivek-Prajapatii, can you update your GitHub profile picture so you show up in the Contributors?

**Comment by sonnynomnom** [comment]
@Vivek-Prajapatii ^

**Pull request merged**
