### PR TITLE
Python: Add `random.choice()`

### PR DESCRIPTION
**Pull request by balapriyac**
### Description

Add `random.choice()` that helps sample an element at random from Python's random module

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by balapriyac** [comment]
@yangc95 Hi Yang, could you please let me know if everything looks fine, or would you like me to provide additional context on any of the changes?
I found that the `choice` method was not added to the `random` module docs already available. Hence, wanted to add it. Also, could you pls clarify if you'd be accepting contributions to this project as part of Hacktoberfest?
I've been looking for projects to contribute towards improving and adding documentation, and I'm glad I found this project.

**Comment by yangc95** [comment]
Wow @balapriyac! Great job with this one; I liked all the code snippet/codebyte examples and this entry will make a nice addition to the Python docs.

Going to pass this on to your next reviewer!

**Comment by balapriyac** [comment]
> Wow @balapriyac! Great job with this one; I liked all the code snippet/codebyte examples and this entry will make a nice addition to the Python docs.
> 
> Going to pass this on to your next reviewer!

Thank you very much @yangc95.

**Comment by balapriyac** [comment]
Hi @Dusch4593, thank you very much for all the suggestions. They were super helpful.
I've resolved them all. Could you pls check if it looks okay now?

**Comment by balapriyac** [comment]
Hi @yangc95, would you be doing the final review as well for this entry? 😄

**Comment by Dusch4593** [comment]
> Hi @yangc95, would you be doing the final review as well for this entry? 😄

Nope, I'll defer to @sonnynomnom on that one.

**Comment by sonnynomnom** [comment]
Merged! Congrats @balapriyac. It's currently live here: https://www.codecademy.com/resources/docs/python/random-module/choice 🤙

I also made some more edits: https://github.com/Codecademy/docs/commit/a8cda7cc442ec70bee1b3459869344ff2174a86c
- Updated the metadata Description so that it opens with a verb and also no single ticks.
Screen Shot 2021-10-19 at 2 42 18 PM
- Slightly formatted the Codebyte Example a little differently to fit the Codebyte better.
- Added some newlines.

Please take a close look @yangc95 @Dusch4593 @balapriyac when you get the chance!

**Pull request merged**
