### PR TITLE
add-lastIndexOf-array-JS

### LINKED ISSUE #356: [Entry] Add lastIndexOf() to Array - JavaScript
## Description

Tests are not passed
Review Needed

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [ ] Labels are added
- [ ] Assignee is added

### PR DESCRIPTION
**Pull request by Keshraf**
### Description

Language: JavaScript
File: concepts/array/terms
Added Folder: lastIndexOf
Added File: lastIndexOf.md
Close #356 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by yangc95** [comment]
> Hello @yangc95 , What is the next step for this PR? Will a reviewer be assigned to it?

Yup, thanks for your patience! I'll be doing the first review for this entry.

**Comment by yangc95** [comment]
@Keshraf done with my review, please tag me once you've made changes!

**Comment by Keshraf** [comment]
> @Keshraf done with my suggestions/comments, please tag me once you've made changes!

@yangc95 I have made the changes you suggested, please go through it and let me know.

**Comment by yangc95** [comment]
> > @Keshraf done with my suggestions/comments, please tag me once you've made changes!
> 
> @yangc95 I have made the changes you suggested, please go through it and let me know.

LGTM! Passing this on to the next reviewer.

**Comment by KTom101** [comment]
@Keshraf Now let's see if we can fix the failing tests. Can you run the following commands and push the changes?

```
npm i 

npm run format:all 
```

**Pull request merged**
