### PR TITLE
Add isFinite.md to JavaScript

### LINKED ISSUE #345: [Entry] isFinite method - JavaScript
## Description

The tests are not passing in Pull Requests

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [ ] Labels are added
- [ ] Assignee is added

### PR DESCRIPTION
**Pull request by Keshraf**
### Description

Language: JavaScript
File: concepts/number-methods/terms
Added Folder: isFinite
Added File: isFinite.md
Close #345 

Pull Request for the Hacktober Fest 2021

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by yangc95** [comment]
Hi @Keshraf, nice job with these JavaScript methods. 

I added some suggestions and comments. When you're finished making corrections, I'll pass this PR on to the next reviewer.

**Comment by Dusch4593** [comment]
Hey @Keshraf! I'm combing through some of the entries that were added at the end of last year and noticed that the name of the contributor listed under [JavaScript Number Methods: `isFinite()`](https://www.codecademy.com/resources/docs/javascript/number-methods/isFinite) is remarkably different from yours? (No matching email or discernible first/last name that can be gathered from either usernames)

Can you confirm that your GitHub account "Keshraf" is using the same email account as the one being used for "ramanLamichhane8756805339" on Codecademy?

**Comment by Keshraf** [comment]
I am not using that account on CodeAcademy.

**Comment by Dusch4593** [comment]
Hmmm, this is interesting. May I ask what username you use on Codecademy, if any?

**Comment by Dusch4593** [comment]
It looks like your all contributors are "Anonymous" on the [.isNan() entry](https://www.codecademy.com/resources/docs/javascript/number-methods/isNaN) as well (also one you initially added to Docs).

**Comment by Keshraf** [comment]
This is my account on Codeacademy

@ketanSaraf0066545912

**Comment by Dusch4593** [comment]
Would you like to do the following when you have time?

1. Sign out of your Codecademy account completely. (but don't log off from GitHub)
2. Log back into Codecademy through the GitHub icon towards the bottom.

After these steps, let me know if you can see your profile credited on any of the entries mentioned. 🤞

**Comment by Keshraf** [comment]
Well I did sign out and log in using GitHub.

**Comment by Dusch4593** [comment]
Awesome! Can you see your profile listed on the entries now?

**Comment by Dusch4593** [comment]
I can sometimes see your profile listed when I refresh. Other times not. But I think that's more of internal problem that needs sorted out on our side.

**Comment by Keshraf** [comment]
Where should I see my profile?

**Comment by Dusch4593** [comment]
Near the top-right under "Contributors"? Check one of the following entries:

* `.isFinite()`: https://www.codecademy.com/resources/docs/javascript/number-methods/isFinite
* `.isInteger()`: https://www.codecademy.com/resources/docs/javascript/number-methods/isInteger
* `.isNan()`: https://www.codecademy.com/resources/docs/javascript/number-methods/isNan

**Comment by Keshraf** [comment]
I can’t see my profile here

**Comment by Dusch4593** [comment]
You can't see what I'm seeing on my end (even after being logged in with GitHub)?

Screen Shot 2022-03-04 at 10 20 29 AM

**Comment by Keshraf** [comment]
Yeah, now I can see it

**Comment by Dusch4593** [comment]
That is excellent to hear! 😃 

One last thing. Did you want to stick with that default image on your Codecademy profile or change to match this cool GH profile image?

**Comment by Keshraf** [comment]
Matching it would be better.

**Comment by Keshraf** [comment]
Thank you for your help

**Comment by Dusch4593** [comment]
@Keshraf Absolute! Happy to help anytime!

**Comment by Keshraf** [comment]
Is there anyway, I can help you?

**Comment by Dusch4593** [comment]
I think all is good on my end of things! 👍 

There's a handful of [open issues in Docs](https://github.com/Codecademy/docs/issues) right now if you're interested. I'm hope to have more filed soon. 😄

**Pull request merged**
