### PR TITLE
Created Documentation for structure(new C++ entry)

### PR DESCRIPTION
**Pull request by Aditya-150**
**Description**
Hey, I found that the documentation for structure is not present in cpp content so I created the documentation for it.
Hope this works.
Happy Coding:)

**Type of Change**
- Adding a new entry

**Checklist**
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Aditya-150** [comment]
@Dusch4593 Thanks for reviewing it, please suggest more changes , if needed

**Comment by Dusch4593** [comment]
> @Dusch4593 Can you add **hacktoberfest-accepted** label on it? It will be great , if you do so..

I'm going to defer this to @sonnynomnom.

**Comment by Aditya-150** [comment]
@yangc95 Should we make more changes to the file? If yes, please suggest.

**Comment by Aditya-150** [comment]
> Merge! Congrats @Aditya-150, it's live here: https://www.codecademy.com/resources/docs/cpp/structure 🚀
> 
> I made a lot of little changes: https://github.com/Codecademy/docs/commit/677c640284b1dbb973f03f3223ab7434fe23fed6
> 
> - Lowercase variable names for all C++ content.
> - Two spaces indentation instead of four.
> - Opening { should also be on the same line for C++.
> - Don't use `using namespace std:` for Codecademy content.
> - Use ```shell for output code blocks.
> 
> Please take a close look! ☝️ @Aditya-150 @Dusch4593 @yangc95 

Thanks @sonnynomnom , @Dusch4593 and @yangc95 for your valuable guidance through out the process. This was my first contribution to any repo.
It was a great experience although.👨‍💻:)

**Pull request merged**
