### PR TITLE
[Entry Request] Java: Inheritance

### PR DESCRIPTION
**Pull request by saurabh042**
Added documentation about Inheritance in Java

### CODE REVIEW

**Comment by saurabh042** [comment]
Hi @sonnynomnom
Thanks for the review. Have committed the suggested changes.

**Comment by saurabh042** [comment]
Hi @Dusch4593 
committed code after running above command.

Thanks

**Comment by yangc95** [comment]
> Hi sonnynomnom Thanks for the review. Have committed the suggested changes.

Hey @saurabh042, I'll be doing a second review before we move on to the next step!

**Comment by sonnynomnom** [comment]
Merged! Congrats @saurabh042 on your entry. It's live [here](https://www.codecademy.com/resources/docs/java/inheritance).

I also made some small changes: https://github.com/Codecademy/docs/commit/a2f92d17ad5e2f78e63fb9810372eec8c093c060

- I updated the title from "Java: Inheritance" to just "Inheritance".
- Broke up a long paragraph.
- Made the type of inheritance from bullet points to subheadings with `###`.

We should be good to go!

One last thing @saurabh042, can you update your GitHub profile picture so that you show up in our Contributors' list?

**Comment by sonnynomnom** [comment]
Screen Shot 2021-11-01 at 6 25 41 PM

**Pull request merged**
