### PR TITLE
Added vector `push_back()` and `insert()` C++ functions

### PR DESCRIPTION
**Pull request by gpr222**
### Description

Added the vector push_back and insert functions

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by sonnynomnom** [comment]
Hi @gpr222, thanks for contributing!

We are a little backed up at the moment, but hopefully, one of our team members will take a look at your entry (review #1) within 48 hours!

**Comment by Dusch4593** [comment]
Hi, @gpr222! Thanks for contributing this edit to our `vectors.md` C++ entry! I just finished the first review and left some comments/suggestions for you to check out. Let us know when you've finished making the changes. 

P.S. For future pull requests, make sure that you are pushing from a branch named after the changes you made. For example, the branch for this PR could have been named `cpp-add-push-back-and-insert`

**Comment by sonnynomnom** [comment]
@gpr222 Congrats! The entry is live: https://www.codecademy.com/resources/docs/cpp/vectors

I also changed `cout` to `std::cout` to follow our style guides.

One last thing @gpr222, can you update your GitHub profile so that you show up in our Contributors' list? 🙏

**Comment by gpr222** [comment]
Hi @sonnynomnom , thanks for helping in making this PR a success. 
Further I would like to know what updations on GitHub profile would be required to show up in the contributors list.

**Comment by sonnynomnom** [comment]
@gpr222 just the profile picture!

Screen Shot 2021-11-01 at 6 24 40 PM

**Pull request merged**
