### PR TITLE
Remove trailing spaces

### PR DESCRIPTION
**Pull request by yangc95**
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by sujeethchauhan** [comment]
changes are made

**Comment by sumanth1710** [comment]
Changes done

**Comment by venkateshpandilla** [comment]
Checklist

**Comment by yangc95** [comment]
@venkateshpandilla did you have a comment or question about the checklist?

**Comment by dmytrosorokame** [comment]
Good changes!

**Comment by engineertang** [comment]
I am learning pull request through coursera course. Github is open for public to demonstrate how a software team work collaboratively.

**Comment by jamesjacob-jack** [comment]
you need to change the begining of the code

**Comment by Yahavarshini** [comment]
Nice work

**Comment by venkateshpandilla** [comment]
Ok I will do it thank you 😃

**Comment by xxieen** [comment]
hi , I am taking a lessen from codecademy

**Comment by Gitsamurai** [comment]
It's 2024 and this content is still golden, as a Codecademy student am getting to appreciate pull requests.

**Comment by don-mo** [comment]
hiiiiiiiiiiiiiiiiiiiii codeacademy epic style

**Comment by don-mo** [comment]
Hi! I'm taking the github pull request course!! Nice job everyone!

**Comment by yiro02** [comment]
good nice course

**Comment by dmwambua** [comment]
works as previously discussed

**Comment by beqa21beraia** [comment]
Nice work, it has to be merged!

**Pull request merged**
