### PR TITLE
docs: added a new general methods entry

### PR DESCRIPTION
**Pull request by thuc-nhu**
### Description

Created a short documentation on What is Methods for the general folder under the content folder. 

Addresses Issue #337

### Type of Change

- Adding a new entry

### Checklist
- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by thuc-nhu** [comment]
@sonnynomnom, no problems. I'll check back and if my entry checks out with you guys, I can do another entry.

**Comment by thuc-nhu** [comment]
@Dusch4593 I made the changes but verify_formating keeps failing. I tried to run yarn format on my local files but am running into an error with 'prettier' not being an internal or external command, operable program, or batch file. 

Sorry, new to this. Thanks.

**Comment by thuc-nhu** [comment]
@Dusch4593 That works. Thanks. Ready for the next review.

**Comment by thuc-nhu** [comment]
@Dusch4593 and @SSwiniarski added the varaibles. 
Thanks!

**Comment by sonnynomnom** [comment]
Hi @thuc-nhu, congrats on your entry. 🚀

It just went live: https://www.codecademy.com/resources/docs/general/what-is-a-method

I also made some more changes: https://github.com/Codecademy/docs/commit/eb69730dc51c31f7fe462555f6450d7a56691e7c

Please take a look ^ @thuc-nhu @Dusch4593 @SSwiniarski 

- Changed the title from "Method" to "Methods"
- The second CatalogContent is not showing up so taking out the `/`
- Use dot notation when writing method names and no parameters: `.introduceSelf()` instead of `introduce(self)`
- Added a section at the very bottom

Anyway, we should be good to go here!

**Pull request merged**
